### ISSUE TITLE
Change pinout for RP2040-zero

### ISSUE THREAD

**Issue by vslinuxdotnet** [evansm7/pico-mac#6]
Hello,
Congrats for the project !!!

I have the RP2040-zero board, the default pin config works fine, but is hard to put it in a board because is in the back of the dev board, so i change according the PIO config do pins avaliable, but don't work.
Board: https://www.waveshare.com/wiki/RP2040-Zero

I have include/hw.h:

#define GPIO_LED_PIN    16 //PICO_DEFAULT_LED_PIN
#define GPIO_VID_DATA   10 //18
#define GPIO_VID_VS     11  //19
//#define GPIO_VID_CLK    20
#define GPIO_VID_HS     8 //21

what I doing wrong, or what i need to change in files ?

Thanks, VS

**Comment by evansm7** [comment]
Hi! It could do with a comment (this info is buried in the readme/PIO comments), but the pins must be contiguous and in ascending order of data, VS, CLK, HS. (CLK is unused but that pin has to be assigned due to how the PIO code currently works; ignore it, don’t wire it.)

The waveshare board is nice; perhaps try GP9,10,11,12 across the bottom for Data, VS, clk (no connection), HS.
